services:
  kafka:
    image: apache/kafka:3.7.0-rc2
    container_name: kafka
    ports:
      - "9092:9092"
      - "8083:8083"

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  spark-master:
    image: apache/spark:3.5.0-scala2.12-java11-python3-r-ubuntu
    container_name: spark-master
    environment:
      SPARK_MODE: master

  airflow:
    image: apache/airflow:2.7.0-python3.10
    container_name: airflow_webserver
    ports:
      - "8080:8080"
