services:
  postgres:
    build: ./postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: musicdb
    ports:
      - "5432:5432"
    networks:
      - app_network

  spark-master:
    build: ./spark-master
    container_name: spark-master
    hostname: spark-master
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8080:8080"
      - "8083:8083"
    networks:
      - app_network

  spark-worker:
    build: ./spark-worker
    container_name: spark-worker
    hostname: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - app_network

  mongodb:
    build: ./mongodb
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
