version: "3.8"

services:
  kafka:
    image: apache/kafka:3.7.0-rc2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  debezium:
    image: debezium/connect:2.4
    container_name: debezium_connect
    depends_on:
      - kafka
      - postgres
      - mongodb
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID_CONFIG: connect-cluster-group-id
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-statuses

  spark-master:
    image: apache/spark:3.5.0-scala2.12-java11-python3-r-ubuntu
    container_name: spark-master
    environment:
      SPARK_MODE: master

  airflow:
    image: apache/airflow:2.7.0-python3.10
    container_name: airflow_webserver
    ports:
      - "8080:8080"
